# Numpy


The Numpy is a python library.
- Numpy stand for Numerical pyathon 
-  NumPy provides built-in support for linear algebra,
- statistics, trigonometric functions, and random number generation.
- It is open source and you can easily use 
- Numpay is created by 2005 by travis oilphant.

In [14]:
# import numpy
import numpy as np

In [15]:
# create numpay array from a list.
arr_list = [1,2,3,4,5]
print(type(arr_list))
print(arr_list)

<class 'list'>
[1, 2, 3, 4, 5]


In [16]:
mylist= np.array(arr_list)
print(type(mylist))
print(mylist)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [19]:
matrix =[1,2,3],[4,4,6],[7,8,9]
print(matrix)

([1, 2, 3], [4, 4, 6], [7, 8, 9])


In [20]:
matrix_arr = np.array(matrix)
print(type(matrix_arr))
print(matrix_arr)

      

<class 'numpy.ndarray'>
[[1 2 3]
 [4 4 6]
 [7 8 9]]


In [12]:
# 1_d array
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
import numpy as np
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [129]:
# 2_d array
np.zeros(0)

array([], dtype=float64)

In [15]:
# 3_d array
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
#  use this linspace
import numpy as np
np.linspace(0, 10,3)

array([ 0.,  5., 10.])

In [26]:
# identify matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# genrate random number,
# rand (deciml 0 to 1)
# 1D array 
np.random.rand(5)


array([0.21681557, 0.15477264, 0.9254834 , 0.11716872, 0.45475032])

In [29]:
np.random.rand(1)

array([0.27100788])

In [31]:
np.random.rand(4,4) # given matrix 4 rows and 4 columns
                    # np.random.rand(it is use genrate decimal number between 0 and 1 in numpy).

array([[0.17164591, 0.47250419, 0.30137479, 0.29492892],
       [0.69481852, 0.58682131, 0.14284407, 0.72628088],
       [0.39167729, 0.40483792, 0.59240448, 0.0927471 ],
       [0.66539649, 0.65945947, 0.00108275, 0.418594  ]])

In [38]:
np.random.randint(0,100,(3,4)) # 3*4 by matrix grenrate rondom integers 

array([[69, 49, 76, 71],
       [99, 42, 40, 43],
       [19,  4, 98, 91]], dtype=int32)

In [40]:
np.random.seed(12) # seed (fixing the  starting point random numbers genrate)
np.random.rand(4) # rand (genrate 4 random numbers in o to 1) 

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [49]:
# reshaped array print
arr = np.arange(0,25)  # arange (print to 0 to 49 not include in above 50)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [54]:
arr.reshape(5,5) # arr.reshape( 1d array matrix  format print )

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
# find the highst and lowest number in this position
arr =np.random.randint(0,101 ,10)
print(arr)

[76 48 22 49 52  5 13 89 34 75]


In [57]:
print("max:",arr.max())                      # print highst number
print("min:",arr.min())                      # print lowest number 
print("argmax(index of max):",arr.argmax())  # argemax(largest number and this postion  (counting start 0))
print("argmin(index of min):",arr.argmin())  # argemin(find lowest number and this postion (counting start from 0) )


max: 89
min: 5
argmax(index of max): 7
argmin(index of min): 5


# Numpy indexing and selction

In [120]:
arr = np.arange(0, 11) # print 0 to 10 numbers
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [61]:
arr[4] 

np.int64(4)

In [62]:
arr[:5]  # print array 0 to 5

array([0, 1, 2, 3, 4])

In [64]:
arr[::-1] # print  reverse number 10 to 0

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [65]:
arr[::1] # print 0 to 10 number

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr_2d.shape 

(3, 3)

In [79]:
arr_2d[0]

array([1, 2, 3])

In [81]:
arr_2d[0,2]

np.int64(3)

In [83]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [85]:
arr =np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[arr>4] # print grater than 4

array([ 5,  6,  7,  8,  9, 10])

# Numpay opration

In [115]:
arr =np.arange(0,11)
arr
print(type(arr))

<class 'numpy.ndarray'>


In [90]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [91]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr *arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [93]:
arr / arr

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_15356\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
np.sqrt(arr) # square root 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [95]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [96]:
arr.sum()

np.int64(55)

In [97]:
arr.mean() # calculate avrage 

np.float64(5.0)

In [98]:
arr.max()

np.int64(10)

In [114]:
arr.std() # standard deviation 
print(type(arr.std()))

<class 'numpy.float64'>


In [103]:
arr .var() # calculate variance

np.float64(10.0)

In [105]:
arr_2d =np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
arr_2d.sum()

np.int64(300)

In [113]:
arr_2d.sum(axis=0)
print(type(arr_2d))

<class 'numpy.ndarray'>


In [112]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])